[profile.default]
src = "src"
out = "out"
libs = ["../../lib"]
allow_paths = ["../"]

via_ir = true
optimizer_runs = 20_000
ffi = true

solc_version = "0.8.26"
evm_version = "cancun"
bytecode_hash = "none"

auto_detect_remappings = false
