[profile.default]
src = "src"
out = "out"
libs = ["../../lib"]
allow_paths = ["../"]

solc_version = "0.8.26"
optimizer_runs = 25_666
via_ir = true
ffi = true

evm_version = "cancun"
gas_limit = "300000000"
bytecode_hash = "none"

auto_detect_remappings = false
